#!/usr/local/bin/ruby

require 'rubygems'

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

# require rack 1.0.1 explicitly
gem 'rack', '1.0.1'

gem 'unicorn', version
load Gem.bin_path('unicorn', 'unicorn_rails', version)
